jimengio/rough-table

- package.json
- src/rough-div-table.tsx
- yarn.lock
Preview http://fe.jimu.io/rough-table/ .
> add empty icon; alpha release

- example/controller/generated-router.ts
- example/gen-router.ts
- example/models/router-rules.ts
- example/pages/container.tsx
- example/pages/pages/basic.tsx
- example/pages/pages/empty.tsx
- example/pages/pages/paginated.tsx
- example/pages/pages/selected.tsx
- example/pages/pages/whole-borders.tsx
- package.json
- src/rough-div-table.tsx
- tsconfig.json
- webpack/dev.js
- webpack/release.js
- webpack/router-config.js
- yarn.lock
New page http://fe.jimu.io/rough-table/#/paginated
> divider into pages with sidebar

- package.json
Previews http://fe.jimu.io/rough-table/#/whole-borders
> alpha release for wholeBorders property

- example/controller/generated-router.ts
- example/models/router-rules.ts
- example/pages/container.tsx
- example/pages/pages/wide.tsx
- package.json
- src/rough-div-table.tsx
Previews http://fe.jimu.io/rough-table/#/wide
> Refine scroll area

- example/pages/pages/selected.tsx
- src/action-links.tsx
and update example
review: [@jimengio/rough-table@0.1.5-a1](https://www.npmjs.com/package/@jimengio/rough-table/v/0.1.5-a1)
> feat(action-links): callback onClick event

- package.json
- src/rough-div-table.tsx
```
+ @jimengio/rough-table@0.1.6-a1
```
> add flex-basis for unifying cell widths; alpha release

- example/pages/pages/tree-table.tsx
- package.json
- src/index.ts
Previews http://fe.jimu.io/rough-table/#/tree-table .
> adding docs for tree-table; export types; alpha release

- example/pages/pages/basic.tsx
http://fe.jimu.io/rough-table/#/basic
> doc: config column width

- package.json
- src/rough-div-table.tsx
- src/rough-tree-table.tsx
- src/scroll-div-table.tsx
ScrollDivTable 同步一些 DivTable 的更新. 在 DivTable 当中调整 body 的 scroll 样式.
> refine table styles; add overflow:auto in body

- example/pages/demo/basic.tsx
- package.json
- src/rough-div-table.tsx
Previews http://fe.jimu.io/rough-table/#/basic .
模仿 antd table 的居中行为.
> align content vertically center in cells; alpha release

- example/pages/demo/tree-table.tsx
- package.json
- src/rough-tree-table.tsx
> controlling size of cells in the tree column; alpha release

- example/pages/demo/basic.tsx
http://fe.jimu.io/rough-table/#/basic
> demo for hidden property

- example/pages/demo/wide.tsx
- package.json
- src/rough-div-table.tsx
Previews http://fe.jimu.io/rough-table/#/wide (latest demo).
效果不完美, 高亮区域不对. 勉强算修复了 bug.
> fix duplicated scrollbar in narrow tables; release 0.2.13

- example/controller/generated-router.ts
- example/models/router-rules.ts
- example/pages/container.tsx
- example/pages/demo/basic.tsx
- example/pages/demo/row-resizing.tsx
- package.json
- src/rough-div-table.tsx
- src/scroll-div-table.tsx
Add a `minWidth` to make sure width expends to the whole width area.
目前的思路是监听 window resize 然后强行对 row 的位置进行调整, 可能有性能问题, 暂时先试验.
> trying to add width and backgrounds when scrollbar appears

- example/controller/generated-router.ts
- example/models/router-rules.ts
- example/pages/container.tsx
- example/pages/demo/basic.tsx
- example/pages/demo/configure.tsx
- example/pages/demo/selected.tsx
- package.json
- src/index.ts
- src/rough-div-table.tsx
通过 API 可以设置作为 DivTable 默认参数, 不需要每个组件单独写:
```js
configureDivTableProps({
rowPadding: 80,
wholeBorders: true,
showEmptySymbol: true,
emptyLocale: "Just empty",
});
```
> add configureDivTableProps; alpha release

- example/pages/demo/configure.tsx
- package.json
- src/action-links.tsx
```ts
configureActionLinksProps({
spaced: true
});
```
> API for configure link default props; alpha release

- example/controller/generated-router.ts
- example/models/router-rules.ts
- example/pages/container.tsx
- example/pages/demo/empty-placeholder.tsx
- package.json
- src/common.tsx
- src/empty-placeholder.tsx
- src/index.ts
- src/rough-div-table.tsx
- src/rough-table.tsx
- src/scroll-div-table.tsx
优化了一下样式, 免得高度被挤压的情况出现. 另外暴露方便复用.
> refine style of no data; alpha release

- package.json
- src/rough-div-table.tsx
- src/scroll-div-table.tsx
> handle error caused by empty data

- example/main.tsx
- package.json
- src/common.tsx
- src/hooks/column-resize.tsx
- src/rough-div-table.tsx
- yarn.lock
Previews http://fe.jimu.io/rough-table/#/basic .
> initial working version for resizable columns

- src/action-links.tsx
- src/rough-div-table.tsx
- src/scroll-div-table.tsx
* `data-area` 表格区域.
* `data-action` 链接点击行为.
> add data-action for link buttons

- example/pages/custom-theme.tsx
- example/pages/demo/basic.tsx
- package.json
- src/common.tsx
- src/hooks/column-resize.tsx
- src/rough-div-table.tsx
> expose className slots for highly customized style

- example/pages/custom-theme.tsx
- package.json
- src/empty-placeholder.tsx
- src/rough-div-table.tsx
- src/theme.ts
> support customizing loading styles

- example/controller/generated-router.ts
- example/models/router-rules.ts
- example/pages/container.tsx
- example/pages/demo/align-to-right.tsx
- package.json
- src/hooks/column-resize.tsx
- src/rough-div-table.tsx
Previews http://fe.jimu.io/rough-table/#/align-to-right .
Should look more consistent being provided by a configuration.
> add alignToRight property; alpha release

- package.json
- src/rough-div-table.tsx
> 修复边框模式下，分页左右会出现边框bug
